package com.example.animation.LIB


import android.content.Context
import android.view.View
import android.view.animation.Animation
import android.view.animation.AnimationUtils
import com.example.animation.R


class AnimationKC( context: Context) {
    val fadein = AnimationUtils.loadAnimation(context, R.anim.fadein)
    val fadein_with_last_state = AnimationUtils.loadAnimation(context, R.anim.fadein_with_last_state)
    val fadeout=AnimationUtils.loadAnimation(context, R.anim.fadeout)
    val fadeout_with_last_state=AnimationUtils.loadAnimation(context, R.anim.fadeoutwithstate)
    val toup=AnimationUtils.loadAnimation(context, R.anim.toup)
    val toup_with_fadeout=AnimationUtils.loadAnimation(context, R.anim.toup_with_fadein)
    val toup_with_fadeout_with_state=AnimationUtils.loadAnimation(context, R.anim.toupwithfadewithstate)
    val todown=AnimationUtils.loadAnimation(context, R.anim.todown)
    val todown_with_fadein=AnimationUtils.loadAnimation(context, R.anim.todown_with_fade)
    val todown_with_fadein_with_state=AnimationUtils.loadAnimation(context, R.anim.todownwithfadewithstate)
    val toright=AnimationUtils.loadAnimation(context, R.anim.toright)
    val go_out_from_right=AnimationUtils.loadAnimation(context, R.anim.outtoright)
    val toleft=AnimationUtils.loadAnimation(context, R.anim.toleft)
    val go_out_from_left=AnimationUtils.loadAnimation(context, R.anim.outtoleft)
    val go_out_from_left_with_state=AnimationUtils.loadAnimation(context, R.anim.outleftwithsatae)
    val go_out_from_right_with_state=AnimationUtils.loadAnimation(context, R.anim.outrightwithstate)
    val zero_to_origal=AnimationUtils.loadAnimation(context, R.anim.zero_to_orignal)
    val orignal_to_zero=AnimationUtils.loadAnimation(context, R.anim.orignal_to_zero)
    val orignal_to_zero_with_state=AnimationUtils.loadAnimation(context, R.anim.orignal_to_zero_with_state)
    val rotate90=AnimationUtils.loadAnimation(context, R.anim.rotate90)
    val rotate90_with_state=AnimationUtils.loadAnimation(context, R.anim.rotate90withstate)
    val rotate90_from_top=AnimationUtils.loadAnimation(context, R.anim.rotate90fromtop)
    val rotate90_from_bottom=AnimationUtils.loadAnimation(context, R.anim.rotate90frombottom)
    val rotate180=AnimationUtils.loadAnimation(context, R.anim.rotate180)
    val rotate180_from_top=AnimationUtils.loadAnimation(context, R.anim.rotate180fromtop)
    val rotate180_from_bottom=AnimationUtils.loadAnimation(context, R.anim.rotate180frombottom)
    val rotate270=AnimationUtils.loadAnimation(context, R.anim.rotate270)
    val rotate270_from_top=AnimationUtils.loadAnimation(context, R.anim.rotate270fromtop)
    val rotate270_from_bottom=AnimationUtils.loadAnimation(context, R.anim.rotate270frombottom)
    val rotate360=AnimationUtils.loadAnimation(context, R.anim.rotate360)
    val rotate360_from_top=AnimationUtils.loadAnimation(context, R.anim.rotate360fromtop)
    val rotate360_from_bottom=AnimationUtils.loadAnimation(context, R.anim.rotate360frombottom)

    val long_fadein = AnimationUtils.loadAnimation(context, R.anim.long_fadein)
    val long_fadein_with_last_state = AnimationUtils.loadAnimation(context, R.anim.long_fadein_with_last_state)
    val long_fadeout=AnimationUtils.loadAnimation(context, R.anim.long_fadeout)
    val long_fadeout_with_last_state=AnimationUtils.loadAnimation(context, R.anim.long_fadeoutwithstate)
    val long_toup=AnimationUtils.loadAnimation(context, R.anim.long_toup)
    val long_toup_with_fadeout=AnimationUtils.loadAnimation(context, R.anim.long_toup_with_fadein)
    val long_toup_with_fadeout_with_state=AnimationUtils.loadAnimation(context, R.anim.long_toupwithfadewithstate)
    val long_todown=AnimationUtils.loadAnimation(context, R.anim.long_todown)
    val long_todown_with_fadein=AnimationUtils.loadAnimation(context, R.anim.long_todown_with_fade)
    val long_todown_with_fadein_with_state=AnimationUtils.loadAnimation(context, R.anim.long_todownwithfadewithstate)
    val long_toright=AnimationUtils.loadAnimation(context, R.anim.long_toright)
    val long_go_out_from_right=AnimationUtils.loadAnimation(context, R.anim.long_outtoright)
    val long_toleft=AnimationUtils.loadAnimation(context, R.anim.long_toleft)
    val long_go_out_from_left=AnimationUtils.loadAnimation(context, R.anim.long_outtoleft)
    val long_go_out_from_left_with_state=AnimationUtils.loadAnimation(context, R.anim.long_outleftwithsatae)
    val long_go_out_from_right_with_state=AnimationUtils.loadAnimation(context, R.anim.long_outrightwithstate)
    val long_zero_to_origal=AnimationUtils.loadAnimation(context, R.anim.long_zero_to_orignal)
    val long_orignal_to_zero=AnimationUtils.loadAnimation(context, R.anim.long_orignal_to_zero)
    val long_orignal_to_zero_with_state=AnimationUtils.loadAnimation(context, R.anim.long_orignal_to_zero_with_state)
    val long_rotate90=AnimationUtils.loadAnimation(context, R.anim.long_rotate90)
    val long_rotate90_with_state=AnimationUtils.loadAnimation(context, R.anim.long_rotate90withstate)
    val long_rotate90_from_top=AnimationUtils.loadAnimation(context, R.anim.long_rotate90fromtop)
    val long_rotate90_from_bottom=AnimationUtils.loadAnimation(context, R.anim.long_rotate90frombottom)
    val long_rotate180=AnimationUtils.loadAnimation(context, R.anim.long_rotate180)
    val long_rotate180_from_top=AnimationUtils.loadAnimation(context, R.anim.long_rotate180fromtop)
    val long_rotate180_from_bottom=AnimationUtils.loadAnimation(context, R.anim.long_rotate180frombottom)
    val long_rotate270=AnimationUtils.loadAnimation(context, R.anim.long_rotate270)
    val long_rotate270_from_top=AnimationUtils.loadAnimation(context, R.anim.long_rotate270fromtop)
    val long_rotate270_from_bottom=AnimationUtils.loadAnimation(context, R.anim.long_rotate270frombottom)
    val long_rotate360=AnimationUtils.loadAnimation(context, R.anim.long_rotate360)
    val long_rotate360_from_top=AnimationUtils.loadAnimation(context, R.anim.long_rotate360fromtop)
    val long_rotate360_from_bottom=AnimationUtils.loadAnimation(context, R.anim.long_rotate360frombottom)

    val short_fadein = AnimationUtils.loadAnimation(context, R.anim.short_fadein)
    val short_fadein_with_last_state = AnimationUtils.loadAnimation(context, R.anim.short_fadein_with_last_state)
    val short_fadeout=AnimationUtils.loadAnimation(context, R.anim.short_fadeout)
    val short_fadeout_with_last_state=AnimationUtils.loadAnimation(context, R.anim.short_fadeoutwithstate)
    val short_toup=AnimationUtils.loadAnimation(context, R.anim.short_toup)
    val short_toup_with_fadeout=AnimationUtils.loadAnimation(context, R.anim.short_toup_with_fadein)
    val short_toup_with_fadeout_with_state=AnimationUtils.loadAnimation(context, R.anim.short_toupwithfadewithstate)
    val short_todown=AnimationUtils.loadAnimation(context, R.anim.short_todown)
    val short_todown_with_fadein=AnimationUtils.loadAnimation(context, R.anim.short_todown_with_fade)
    val short_todown_with_fadein_with_state=AnimationUtils.loadAnimation(context, R.anim.short_todownwithfadewithstate)
    val short_toright=AnimationUtils.loadAnimation(context, R.anim.short_toright)
    val short_go_out_from_right=AnimationUtils.loadAnimation(context, R.anim.short_outtoright)
    val short_toleft=AnimationUtils.loadAnimation(context, R.anim.short_toleft)
    val short_go_out_from_left=AnimationUtils.loadAnimation(context, R.anim.short_outtoleft)
    val short_go_out_from_left_with_state=AnimationUtils.loadAnimation(context, R.anim.short_outleftwithsatae)
    val short_go_out_from_right_with_state=AnimationUtils.loadAnimation(context, R.anim.short_outrightwithstate)
    val short_zero_to_origal=AnimationUtils.loadAnimation(context, R.anim.short_zero_to_orignal)
    val short_orignal_to_zero=AnimationUtils.loadAnimation(context, R.anim.short_orignal_to_zero)
    val short_orignal_to_zero_with_state=AnimationUtils.loadAnimation(context, R.anim.short_orignal_to_zero_with_state)
    val short_rotate90=AnimationUtils.loadAnimation(context, R.anim.short_rotate90)
    val short_rotate90_with_state=AnimationUtils.loadAnimation(context, R.anim.short_rotate90withstate)
    val short_rotate90_from_top=AnimationUtils.loadAnimation(context, R.anim.short_rotate90fromtop)
    val short_rotate90_from_bottom=AnimationUtils.loadAnimation(context, R.anim.short_rotate90frombottom)
    val short_rotate180=AnimationUtils.loadAnimation(context, R.anim.short_rotate180)
    val short_rotate180_from_top=AnimationUtils.loadAnimation(context, R.anim.short_rotate180fromtop)
    val short_rotate180_from_bottom=AnimationUtils.loadAnimation(context, R.anim.short_rotate180frombottom)
    val short_rotate270=AnimationUtils.loadAnimation(context, R.anim.short_rotate270)
    val short_rotate270_from_top=AnimationUtils.loadAnimation(context, R.anim.short_rotate270fromtop)
    val short_rotate270_from_bottom=AnimationUtils.loadAnimation(context, R.anim.short_rotate270frombottom)
    val short_rotate360=AnimationUtils.loadAnimation(context, R.anim.short_rotate360)
    val short_rotate360_from_top=AnimationUtils.loadAnimation(context, R.anim.short_rotate360fromtop)
    val short_rotate360_from_bottom=AnimationUtils.loadAnimation(context, R.anim.short_rotate360frombottom)



    fun AnimationStater(View:View,animatation:Animation)
    {
        View.startAnimation(animatation)
    }
}